name = "droscra"
main = "src/server/index.ts"
compatibility_date = "2025-05-07"

[[durable_objects.bindings]]
class_name = "DroscraObj"
name = "DROSCRA_OBJ"

[assets]
directory = "src/client/"
binding = "assets"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DroscraObj"]
