name = "scraper-worker"
main = "src/index.ts"
compatibility_date = "2025-05-10"
compatibility_flags = [ "nodejs_compat"]

browser = { binding = "MYBROWSER" }

[[migrations]]
tag = "v1"
new_classes = ["Browser"]
