name = "droscra"
main = "src/server/index.ts"
compatibility_date = "2025-05-07"

[observability]
enabled = true

[env.staging.vars]
DEBUG = true

[[durable_objects.bindings]]
class_name = "DroscraObj"
name = "DROSCRA_OBJ"

[build]
command = "npm run build"

[assets]
directory = "./build"
binding = "assets"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["DroscraObj"]
